# Generated by Django 5.0.5 on 2024-05-12 10:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0008_newsletter'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='NewsLetter',
            new_name='NewsLetterUser',
        ),
    ]
