# Generated by Django 5.0.5 on 2024-05-12 10:19

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0010_newsletter'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='newsletter',
            name='date_created',
        ),
        migrations.AddField(
            model_name='newsletter',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
