# Generated by Django 5.0.5 on 2024-05-12 11:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0011_remove_newsletter_date_created_newsletter_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='newsletter',
            name='receiver',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
    ]
