# Generated by Django 5.0.5 on 2024-05-13 04:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0012_newsletter_receiver'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='tracking_link',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Tracking Link'),
        ),
    ]
