# Generated by Django 5.0.5 on 2024-05-13 04:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0013_order_tracking_link'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='tracking_link',
            field=models.CharField(default='#', max_length=200, verbose_name='Tracking Link'),
        ),
    ]
