# Generated by Django 5.0.5 on 2024-05-15 10:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0014_alter_order_tracking_link'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='payment_id',
            field=models.CharField(default='COD', max_length=255, verbose_name='Payment ID'),
        ),
    ]
