# Generated by Django 5.0.5 on 2024-05-15 19:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0015_order_payment_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='feedback',
            name='product_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='feedback',
            name='product_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
